# Generated by Django 5.1.3 on 2024-11-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_book_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
