# Generated by Django 5.1.3 on 2024-12-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Price',
            new_name='price',
        ),
    ]
